export const DayIcons = {
  airplane: "airplane",
  baby: "baby-carriage",
  calendar: "calendar",
  camera: "camera",
  camping: "campfire",
  christmas: "pine-tree",
  clock: "clock",
  cross: "cross",
  earth: "earth",
  familyMany: "account-group",
  familySpouse: "account-multiple",
  fire: "fire",
  funeral: "coffin",
  graduation: "school",
  halloween: "halloween",
  heart: "heart",
  map: "map",
  movie: "video-vintage",
  party: "party-popper",
  star: "star",
  vacation: "beach",
  wedding: "ring",
  winter: "snowflake",
};
